public class orayt{

    public static void main(String[] args){
        char [][]OLrayt ={
                {'*'},
            

    {'*'},                  {'*'},


        {'*'},          {'*'},
        };
        for (int i=0; i<OLrayt.length;i++){
            for (int j=0; j<OLrayt[i].length;j++){
                System.out.print(OLrayt[i][j]+" ");
            }
            System.out.println();
        }
}
}